language: rust
rust:
  - 1.42.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace --no-run
  - cargo test --verbose --workspace

os:
  - linux
  - osx

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
