# Successes

[[http]]
url = 'https://eu.httpbin.org/status/200'
status = 200

[[http]]
url = 'https://eu.httpbin.org/status/204'
status = 204

[[http]]
url = 'https://eu.httpbin.org/status/301'
status = 301

[[http]]
url = 'https://eu.httpbin.org/status/304'
status = 304

[[http]]
url = 'https://eu.httpbin.org/status/400'
status = 400

[[http]]
url = 'https://eu.httpbin.org/status/401'
status = 401

[[http]]
url = 'https://eu.httpbin.org/status/403'
status = 403

[[http]]
url = 'https://eu.httpbin.org/status/404'
status = 404

[[http]]
url = 'https://eu.httpbin.org/status/418'
status = 418

[[http]]
url = 'https://eu.httpbin.org/status/500'
status = 500

[[http]]
url = 'https://eu.httpbin.org/status/505'
status = 505


# Failures

[[http]]
url = 'https://eu.httpbin.org/status/200'
status = 204

[[http]]
url = 'https://eu.httpbin.org/status/404'
status = 500
