# success

[[cmd]]
shell = "/testcases/returner.rb 4"
status = 4

[[cmd]]
shell = "/testcases/returner.rb 255"
status = 255

[[cmd]]
shell = "/testcases/returner.rb 0"
status = 0

[[cmd]]
shell = "/testcases/returner.rb 3"


# fails

[[cmd]]
shell = "/testcases/returner.rb 4"
status = 99

[[cmd]]
shell = "/testcases/returner.rb 0"
status = 4

[[cmd]]
shell = "/testcases/returner.rb 4"
status = 0
